# 05d_render_helpers.R
# Rendering and fallback helpers for the 08 multi-agent lab outputs.

render_evidence_packet = function(packet) {
  snapshot_df = packet$live_snapshot
  derived_df = packet$derived_metrics
  market_risk = if ("market_risk" %in% names(packet)) packet$market_risk else NULL
  knowledge_matches = packet$knowledge_matches
  failed_series = if ("failed_series" %in% names(packet)) packet$failed_series else character(0)

  data_source_lines = c(
    paste0("- Source: `", packet$data_source, "`."),
    paste0("- Note: ", packet$source_note),
    paste0(
      "- Window: ",
      packet$date_window$start_date,
      " to ",
      packet$date_window$end_date,
      " with limit ",
      packet$date_window$limit,
      " rows per series."
    ),
    paste0("- Requested series: ", paste(packet$series_requested, collapse = ", "), ".")
  )
  if (length(failed_series) > 0) {
    data_source_lines = c(data_source_lines, paste0("- Missing from live snapshot: ", paste(failed_series, collapse = ", "), "."))
  }
  if ("auxiliary_series" %in% names(packet) && length(packet$auxiliary_series) > 0) {
    data_source_lines = c(data_source_lines, paste0("- Auxiliary series fetched for derived calculations and the risk appendix: ", paste(packet$auxiliary_series, collapse = ", "), "."))
  }

  formula_rules = c(
    "- The raw indicator table below is only a preprocessing view of recent level changes.",
    "- The main macro interpretation should come from the economically meaningful formulas in the next table.",
    "- All derived macro metrics are calculated deterministically in R before the agent writes its summary.",
    "- The SP500/VIX risk appendix is generated by the same custom tool, so it still counts as tool-backed evidence in the 08 lab workflow."
  )

  calculation_df = data.frame(
    Indicator = snapshot_df$series_id,
    `Previous Date` = snapshot_df$previous_date,
    Previous = vapply(snapshot_df$previous_value, format_num, character(1)),
    `Current Date` = snapshot_df$latest_date,
    Current = vapply(snapshot_df$latest_value, format_num, character(1)),
    `Absolute Formula` = snapshot_df$absolute_formula,
    `Percent Formula` = snapshot_df$percent_formula,
    `Absolute Change` = vapply(snapshot_df$absolute_change, format_num, character(1)),
    `Percent Change` = vapply(snapshot_df$percent_change, format_pct, character(1)),
    Direction = snapshot_df$direction,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
  calculation_table = df_as_text(calculation_df)

  if (nrow(derived_df) == 0) {
    derived_table = "| Metric | Value | Formula | Meaning |\n| --- | --- | --- | --- |\n| No macro formulas calculated | NA | NA | The available live snapshot did not support extra derived calculations. |"
    formula_context_table = "| Metric | Textbook Link | Textbook Formula | Why It Matters |\n| --- | --- | --- | --- |\n| No mapped formula reference | NA | NA | NA |"
  } else {
    display_df = data.frame(
      Metric = derived_df$label,
      Value = vapply(derived_df$value, function(x) format_num(x), character(1)),
      Formula = derived_df$formula,
      Meaning = derived_df$meaning,
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
    derived_table = df_as_text(display_df)

    formula_context_rows = lapply(seq_len(nrow(derived_df)), function(i) {
      ref = formula_reference_for_metric(derived_df$metric[[i]])
      data.frame(
        Metric = derived_df$label[[i]],
        `Textbook Link` = paste(ref$topic, "-", ref$formula_label),
        `Textbook Formula` = ref$textbook_formula,
        `Why It Matters` = derived_df$meaning[[i]],
        stringsAsFactors = FALSE,
        check.names = FALSE
      )
    })
    formula_context_df = do.call(rbind, formula_context_rows)
    formula_context_table = df_as_text(formula_context_df)
  }

  if (length(knowledge_matches) > 0) {
    retrieval_context_df = data.frame(
      Topic = vapply(knowledge_matches, function(item) item$entry_id, character(1)),
      `Matched Terms` = vapply(knowledge_matches, function(item) paste(item$matched_terms, collapse = ", "), character(1)),
      `Related Series` = vapply(knowledge_matches, function(item) item$primary_fred_series, character(1)),
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
    retrieval_context_table = df_as_text(retrieval_context_df)
  } else {
    retrieval_context_table = "| Topic | Matched Terms | Related Series |\n| --- | --- | --- |\n| No retrieval context | NA | NA |"
  }

  if (!is.null(market_risk) && isTRUE(market_risk$available) && nrow(market_risk$metrics) > 0) {
    market_metric_table = df_as_text(data.frame(
      Metric = market_risk$metrics$label,
      Value = market_risk$metrics$value,
      Interpretation = market_risk$metrics$meaning,
      stringsAsFactors = FALSE,
      check.names = FALSE
    ))
    market_loss_table = if (nrow(market_risk$worst_losses) > 0) {
      df_as_text(market_risk$worst_losses)
    } else {
      "| Date | SP500 Return | Loss Magnitude |\n| --- | --- | --- |\n| No daily losses available | NA | NA |"
    }
    market_risk_block = paste(
      "## Market Risk Appendix",
      "- This appendix is generated inside the same `build_macro_evidence_packet` custom tool as the macro evidence above.",
      paste0("- Note: ", market_risk$note),
      paste0("- ", market_risk$formula_note),
      market_metric_table,
      "### Worst 5 SP500 Daily Losses",
      market_loss_table,
      sep = "\n"
    )
  } else {
    market_note = if (!is.null(market_risk) && "note" %in% names(market_risk)) market_risk$note else "Market risk appendix was not available for this run."
    market_formula_note = if (!is.null(market_risk) && "formula_note" %in% names(market_risk)) market_risk$formula_note else "Formula trace unavailable."
    market_risk_block = paste(
      "## Market Risk Appendix",
      "- This appendix is generated inside the same `build_macro_evidence_packet` custom tool as the macro evidence above.",
      paste0("- Note: ", market_note),
      paste0("- ", market_formula_note),
      "| Metric | Value | Interpretation |\n| --- | --- | --- |\n| Market risk appendix unavailable | NA | The main macro workflow still ran successfully. |",
      sep = "\n"
    )
  }

  handoff_notes = c(
    paste0("- ", summarize_stance_note(packet)),
    paste0("- Treat `Macroeconomic Formulas Actually Calculated` as the main quantitative evidence, not the context-only level-change table."),
    paste0("- Treat `Market Risk Appendix` as an optional SP500/VIX market proxy, not as portfolio VaR."),
    paste0("- Mention that the evidence packet is based on `", packet$data_source, "` before drawing broader conclusions.")
  )

  paste(
    "# Evidence Packet",
    "## Data Source",
    paste(data_source_lines, collapse = "\n"),
    "## Reading Guide",
    paste(formula_rules, collapse = "\n"),
    "## Recent Level Changes (Context Only)",
    calculation_table,
    "## Macroeconomic Formulas Actually Calculated",
    derived_table,
    market_risk_block,
    "## Supporting Mishkin Formulas Used",
    formula_context_table,
    "## Retrieval Context",
    retrieval_context_table,
    "## Handoff Notes",
    paste(handoff_notes, collapse = "\n"),
    sep = "\n"
  )
}

build_market_risk_brief_section = function(packet) {
  if (!("market_risk" %in% names(packet))) {
    return("")
  }

  market_risk = packet$market_risk
  if (is.null(market_risk) || !isTRUE(market_risk$available) || nrow(market_risk$metrics) == 0) {
    return("")
  }

  metric_value = function(metric_id) {
    rows = market_risk$metrics[market_risk$metrics$metric == metric_id, , drop = FALSE]
    if (nrow(rows) == 0) "NA" else as.character(rows$value[[1]])
  }

  var95 = metric_value("sp500_hist_var_95")
  var99 = metric_value("sp500_hist_var_99")
  latest_vix = metric_value("latest_vix")
  regime = metric_value("vix_regime")

  bullets = c(
    paste0(
      "- SP500 1-day historical VaR is ",
      var95,
      " at 95% and ",
      var99,
      " at 99%, so the appendix adds a simple index-based downside-risk proxy rather than portfolio VaR."
    )
  )

  if (!identical(latest_vix, "NA") && !identical(regime, "NA")) {
    bullets = c(
      bullets,
      paste0(
        "- Latest VIX is ",
        latest_vix,
        ", which points to a ",
        regime,
        " implied-volatility backdrop; the worst-loss table shows the tail days behind that proxy."
      )
    )
  } else {
    bullets = c(
      bullets,
      "- The worst-loss table complements the VaR estimate by showing the largest recent SP500 down days directly."
    )
  }

  paste(c("## Market Risk Appendix", bullets), collapse = "\n")
}

insert_section_before_heading = function(text, section_text, heading = "## Limits") {
  if (!nzchar(section_text)) {
    return(text)
  }

  lines = unlist(strsplit(text, "\n", fixed = TRUE))
  target_idx = which(trimws(lines) == heading)
  if (length(target_idx) == 0) {
    return(paste(text, section_text, sep = "\n"))
  }

  idx = target_idx[[1]]
  before = if (idx > 1) paste(lines[seq_len(idx - 1)], collapse = "\n") else ""
  after = paste(lines[idx:length(lines)], collapse = "\n")

  if (!nzchar(before)) {
    paste(section_text, after, sep = "\n")
  } else {
    paste(before, section_text, after, sep = "\n")
  }
}

ensure_macro_brief_sections = function(brief_text, packet) {
  output = brief_text
  market_section = build_market_risk_brief_section(packet)

  if (!grepl("(?m)^## Limits$", output, perl = TRUE)) {
    limits_lines = c(
      "## Limits",
      paste0("- This brief relies on `", packet$data_source, "` rather than guaranteed live FRED results."),
      paste0("- The evidence window is ", packet$date_window$start_date, " to ", packet$date_window$end_date, ".")
    )
    output = paste(output, paste(limits_lines, collapse = "\n"), sep = "\n")
  }

  if (nzchar(market_section) && !grepl("(?m)^## Market Risk Appendix$", output, perl = TRUE)) {
    output = insert_section_before_heading(output, market_section, heading = "## Limits")
  }

  output
}

extract_section_lines = function(text, heading) {
  lines = unlist(strsplit(text, "\n", fixed = TRUE))
  start_idx = which(trimws(lines) == heading)
  if (length(start_idx) == 0) {
    return(character(0))
  }

  later_headers = which(grepl("^##\\s+", trimws(lines)) & seq_along(lines) > start_idx[1])
  end_idx = if (length(later_headers) > 0) later_headers[1] - 1 else length(lines)

  if (end_idx <= start_idx[1]) {
    return(character(0))
  }

  lines[(start_idx[1] + 1):end_idx]
}

count_bullets = function(lines) {
  sum(grepl("^\\s*-\\s+", lines))
}

is_valid_macro_brief = function(text) {
  required_headers = c("# Macro Brief", "## Key Signals", "## Why It Matters", "## Bottom Line", "## Limits")
  if (!all(vapply(required_headers, function(h) grepl(paste0("(?m)^", gsub("([#])", "\\\\\\1", h), "$"), text, perl = TRUE), logical(1)))) {
    return(FALSE)
  }

  key_lines = extract_section_lines(text, "## Key Signals")
  why_lines = extract_section_lines(text, "## Why It Matters")
  bottom_lines = extract_section_lines(text, "## Bottom Line")
  limits_lines = extract_section_lines(text, "## Limits")

  count_bullets(key_lines) >= 4 &&
    count_bullets(why_lines) >= 3 &&
    nzchar(trimws(paste(bottom_lines, collapse = " "))) &&
    count_bullets(limits_lines) >= 2
}

build_macro_brief_fallback = function(packet) {
  snapshot_df = packet$live_snapshot
  derived_df = packet$derived_metrics

  key_lines = apply(snapshot_df, 1, function(row) {
    paste0(
      "- `", row[["series_id"]], "` is ",
      format_num(as.numeric(row[["latest_value"]])),
      " on ",
      row[["latest_date"]],
      ", versus ",
      format_num(as.numeric(row[["previous_value"]])),
      " previously; change = ",
      format_num(as.numeric(row[["absolute_change"]])),
      " (",
      format_pct(as.numeric(row[["percent_change"]])),
      ")."
    )
  })

  why_lines = character(0)
  if (nrow(derived_df) > 0 && any(derived_df$metric == "cpi_yoy_inflation")) {
    row = derived_df[derived_df$metric == "cpi_yoy_inflation", , drop = FALSE][1, ]
    why_lines = c(why_lines, paste0("- CPI year-over-year inflation is ", format_num(row$value), ", so price pressure is still relevant."))
  }
  if (nrow(derived_df) > 0 && any(derived_df$metric == "real_policy_rate")) {
    row = derived_df[derived_df$metric == "real_policy_rate", , drop = FALSE][1, ]
    why_lines = c(why_lines, paste0("- Real policy rate is ", format_num(row$value), ", which points to restrictive inflation-adjusted policy conditions."))
  }
  if (any(snapshot_df$series_id == "UNRATE")) {
    row = snapshot_df[snapshot_df$series_id == "UNRATE", , drop = FALSE][1, ]
    labor_line = if (row$absolute_change > 0) {
      "- Unemployment moved up, which suggests some softening in the labor market."
    } else if (row$absolute_change < 0) {
      "- Unemployment moved down, which suggests a firmer labor market."
    } else {
      "- Unemployment was stable, so labor conditions do not materially change the interpretation."
    }
    why_lines = c(why_lines, labor_line)
  }
  if (length(why_lines) < 3 && nrow(derived_df) > 0 && any(derived_df$metric == "real_10y_yield")) {
    row = derived_df[derived_df$metric == "real_10y_yield", , drop = FALSE][1, ]
    why_lines = c(why_lines, paste0("- Real 10-year yield is ", format_num(row$value), ", reinforcing the signal from long-term financing conditions."))
  }
  why_lines = why_lines[seq_len(min(3, length(why_lines)))]

  bottom_line = if (packet$data_source == "live_fred") {
    "The combined evidence points to a relatively restrictive macro stance, especially when viewed through the positive real policy rate. Inflation and labor-market signals should still be monitored together before making stronger claims."
  } else {
    "The combined evidence points to a relatively restrictive macro stance, but this run used the demo fallback packet because live FRED access was unavailable. The logic of the workflow is still valid, while the numeric values should be treated as placeholders."
  }

  market_section = build_market_risk_brief_section(packet)

  output = paste(
    "# Macro Brief",
    "## Key Signals",
    paste(key_lines, collapse = "\n"),
    "## Why It Matters",
    paste(why_lines, collapse = "\n"),
    "## Bottom Line",
    bottom_line,
    "## Limits",
    paste0("- This brief relies on `", packet$data_source, "` rather than guaranteed live FRED results."),
    paste0("- The evidence window is ", packet$date_window$start_date, " to ", packet$date_window$end_date, "."),
    sep = "\n"
  )

  if (nzchar(market_section)) {
    output = insert_section_before_heading(output, market_section, heading = "## Limits")
  }

  output
}
